BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBB
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXX X X X XXX XXXXXX X X X X X XXXXXX X X X X XXXXXXX X X X XXXXXXXX XXX X X X XXX XXXXXX X X X X X XXXXXX X X X X XXXXXXX X X X XXXXXXXXXXX
        XXXXX XXXXX XXX X X X X XXXXXXX X X X X X XXXXX X X X XXX XXXXX X X X XXXXXXXXXXX
      XXXXXX
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXX X X X XXX XXXXXX X X X X X XXXXXX X X X X XXXXXXX X X X XXXXXXXX XXX X X X XXX XXXXXX X X X X X XXXXXX X X X X XXXXXXX X X X XXXXXXXXXXX
        XXXXX XXXXXX XXX X X X XXXXXXXXXX X X X XXX XXXXX X X X X X XXXXX X X X X XXXXXXXXX
      XXXXXX
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX X X X X X XXXXXX X X X XXX XXXXX X X X XXXXXXXXX X X X X XXXXXXXXXXX X X X X X XXXXXX X X X XXX XXXXX X X X XXXXXXXXX X X X X XXXXXXXXXX
        XXXXX XXXXXX XXX X X X XXXXXXXXXX X X X XXX XXXXX X X X X X XXXXX X X X X XXXXXXXXX
      XXXXXX
    XXXXXXXXX
  XXXXXX
  XXXXXXXX
    XXX XXXXXXXX X XXX XXXXX
      XXX XXXXXXXXXXXX
      XXXXXXXX X
        XXXXXXXXX XXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXX XXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXX XXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXXXXXXX XXXXXXXX XX X

        X
      X
    XXX
  XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'Algorithms') 
                BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXX
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
         FFFF
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXX
            XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                  XXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X X X X XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX  XXXXXXX XXXXXXX XXX X X X X XXXXXXX XXX X X XXX XXXXXXX XXX X X X XXXXXXXXXX XXXXX XXX X X X XX XXXXXXX XXX X X XXX XXXXXXX XXX X X X XXXXXXXXXXX
                  XXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXX
              XXXXXXXXXXX
                  XXXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX
            XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXXX

        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

          XXXX XXXXXXXXXXXXXXX XXXXXXXXX

            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXX
            XXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX X X X XXX XXXXXX X X X X X XXXXXX X X X X XXXXXXXXX X X X XXXXXXXXXXXXXX X X X X X XXXXXX X X X XXX XXXXX X X X XXXXXXXXXXX X X X X XXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX X X XXXXXXXXXXXXX X X X XXXXXXXXXXX X X X XXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXX XXX X X X X XXXXXXXXX XXX X X X XXX XXXXXXX XXX X X X XX XXXXXXXXXX XXX X X X XXX XXXXXXXX
            XXXXXX
            XXXXXXXXX

            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX

        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX

BBBBBBBB
