BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBB
BBBBBBBB

BBBBB BB
BBBBBBBB

BBBBB BBBBBBB
  XXXXX XXXXXXXXXXXX

    XXXX XXXX XXXXXXXXX XXX X XXXXXXX XXXXXXXXX XXXXXXX XX XXXX XX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX XX X XXXXXXXX XXX X XXXXXX XXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXX XX XXXXXXXX X XXXXX XXXXXXX XXXXXX X XXXXXXXXX XXX XXXXX XXXXXXXXXX XXXXXX XX XXXXXXXX XXX XX XX X XXXXXXXX XXXXX XX XXXXXX XXXXXXXXX XXXX XXXXXXXXXXX
        XXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXX XXX XX XXXXXXX XXX
      XXXX XXXXXXXXXXXX
        BBB BBBBBBBBB BB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXXXXXXX XX XXXX XXX XX XXXXX XXXXXXX XX XXXX XXXXXX XXXXX XXXXXXXX XXXXXX XX XXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXX XX XXXXXXXXX XXXXX XXXXX XXX XXXX XXXXXX XXXXX XXXXX XXX XXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXX XXX XXXX XXXX XXXX
          XXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
        XXXXXX
        BBBBBB
      XXXXXX

      XXXX

    XXXXXX XXXX XXXXXXXXXX XXX

  XXXXXXX
BBBBBBBB
