# Generated by Django 3.0.6 on 2020-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithms',
            name='name_ru',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
