# Generated by Django 3.0.6 on 2020-06-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_algorithms_name_ru'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Algorithms',
            new_name='Algorithm',
        ),
    ]
