# Generated by Django 3.0.6 on 2020-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_auto_20200601_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='clean_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
