# Generated by Django 3.0.6 on 2020-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_algorithm_realization'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
