# Generated by Django 3.0.6 on 2020-06-04 14:53

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0009_auto_20200603_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 4, 14, 53, 41, 710142)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='text_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='text_ru',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
