# Generated by Django 3.0.6 on 2020-06-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0010_auto_20200604_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='realization',
            new_name='java',
        ),
    ]
