# Generated by Django 3.0.6 on 2020-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0011_auto_20200604_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='python',
            field=models.TextField(blank=True, null=True),
        ),
    ]
