# Generated by Django 3.0.6 on 2020-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0012_algorithm_python'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='cpp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
