# Generated by Django 3.0.6 on 2020-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0014_algorithm_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
