# Generated by Django 3.0.7 on 2020-06-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0015_auto_20200611_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='cpp',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='java',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='python',
        ),
    ]
