# Generated by Django 3.0.7 on 2020-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0016_auto_20200612_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='entity',
            field=models.SmallIntegerField(choices=[(1, 'Алгоритм'), (2, 'Структура данных')], default=1),
        ),
    ]
