# Generated by Django 3.0.7 on 2020-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0018_auto_20200615_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='playground',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'binary-heap')], null=True),
        ),
    ]
