# Generated by Django 3.0.7 on 2020-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0020_auto_20200618_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='entity',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Algorithm'), (2, 'Data structure'), (3, 'Data type')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='playground',
            field=models.CharField(blank=True, choices=[('binary-heap', 'BinaryHeap'), ('shuffling', 'Shuffling')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
