# Generated by Django 3.0.7 on 2020-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0021_auto_20200627_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='entity',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Algorithm'), (2, 'Data structure'), (3, 'Abstract data type')], null=True),
        ),
    ]
