# Generated by Django 3.0.7 on 2020-07-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0022_auto_20200710_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='playground',
            field=models.CharField(blank=True, choices=[('binary-heap', 'BinaryHeap'), ('linked-list', 'LinkedList'), ('shuffling', 'Shuffling')], max_length=255, null=True),
        ),
    ]
