# Generated by Django 3.0.7 on 2020-08-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0023_auto_20200712_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='algorithm',
            old_name='name_ru',
            new_name='title_ru',
        ),
    ]
