# Generated by Django 3.0.7 on 2020-09-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0024_auto_20200809_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='modified',
            new_name='mod_date',
        ),
        migrations.RenameField(
            model_name='algorithm',
            old_name='created',
            new_name='pub_date',
        ),
    ]
