# Generated by Django 3.1.1 on 2020-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0026_auto_20200913_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
