# Generated by Django 3.1.1 on 2020-10-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('algorithms', '0028_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Page',
        ),
    ]
