# Generated by Django 3.1.1 on 2020-10-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0029_auto_20201005_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='clean_url',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='clean_url',
            new_name='path',
        ),
    ]
